import { Metadata } from "next";
import Container from "@/components/container";
import NewJobForm from "@/components/new-job-form";
import { CheckCircleIcon } from "@heroicons/react/24/outline";
import { Button } from "@/components/ui/button";

export const metadata: Metadata = {
  title: "Post a Job",
  description: "Generated by create next app",
};

export default function NewJob() {
  return (
    <Container>
      <div className="grid grid-cols-3 gap-3 pb-10">
        <div className="border p-3 rounded-xl">
          <h2 className="text-center font-semibold text-xl">Free</h2>

          <ul className="space-y-3 mt-3">
            <li className="flex gap-2">
              <CheckCircleIcon width={22} />
              Listing for 30 days
            </li>
            <li className="flex gap-2">
              <CheckCircleIcon width={22} />
              Newsletter
            </li>
          </ul>
          <Button className="mt-5" variant="outline">
            Post a job
          </Button>
        </div>

        <div className="border p-3 rounded-xl">
          <h2 className="text-center font-semibold text-xl">Featured</h2>

          <ul className="space-y-3 mt-3">
            <li className="flex gap-2">
              <CheckCircleIcon width={22} />
              Listing for 30 days
            </li>
            <li className="flex gap-2">
              <CheckCircleIcon width={22} />
              Newsletter
            </li>
            <li className="flex gap-2 font-semibold">
              <CheckCircleIcon width={22} />
              30 days on top
            </li>
          </ul>
          <Button className="mt-5">Post a job - $99</Button>
        </div>

        <div className="border p-3 rounded-xl">
          <h2 className="text-center font-semibold text-xl">Pro</h2>

          <ul className="space-y-3 mt-3">
            <li className="flex gap-2">
              <CheckCircleIcon width={22} />
              Listing for 30 days
            </li>
            <li className="flex gap-2">
              <CheckCircleIcon width={22} />
              Newsletter
            </li>
            <li className="flex gap-2 font-semibold">
              <CheckCircleIcon width={22} />
              30 days on top
            </li>
            <li className="flex gap-2 font-semibold">
              <CheckCircleIcon width={22} />
              Custom logo
            </li>
          </ul>
          <Button className="mt-5" variant="green">
            Post a job - $199
          </Button>
        </div>
      </div>
      <NewJobForm />
    </Container>
  );
}
